sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tKbMcUqZgDJuNNRtq8N
    access-key-secret: xM7rqt1GETiUqskTczjgrIx4DjKDRN
    bucket-name: wei-yang
  redis:
    host: 127.0.0.1
    port: 6379
    auth: 123456
    database: 0